### ISSUE TITLE
Using an existing entrypoint in your container

### ISSUE THREAD

**Issue by lktslionel** [Yelp/dumb-init#124]
Is it possible to add an existing entrypoint script as [tini](https://github.com/krallin/tini#existing-entrypoint) is doing ? 

`ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]`

Thanks

**Comment by asottile** [comment]
Yes this should work great with dumb-init as well.  Are you seeing any issues?

**Comment by lktslionel** [comment]
Great thanks for your answer.

**Comment by llatasa** [comment]
Hi,

I know this thread is old, but maybe you can help me.

This is my entrypoint in the Dockerfile:

`ENTRYPOINT ["/usr/bin/dumb-init", "--", "/init"]`

/init is a script that creates folders, execute some other scripts, and eventually it executes the command:

```
trap 'execute_finish_scripts' TERM HUP INT QUIT USR1 USR2
"$@"
```

The container executes the command properly, but signals are not being received anymore. The idea is that I could do some other things before stopping the container (when the stop signal is received). 

Do you know what the problem can be?

Thanks!
