### ISSUE TITLE
manylinux wheel?

### ISSUE THREAD

**Issue by asottile** [Yelp/dumb-init#130]
Figure we might as well :)

Here's how I do this for libsass: https://github.com/dahlia/libsass-python/blob/e9b7421798c03f922e10ce440629520074efd90e/build_manylinux_wheels.py

**Comment by chriskuehl** [comment]
How do you feel about statically compiling (and still tagging as manylinux1) vs. building specifically for the manylinux1 CentOS platform? Currently our wheels are already statically compiled.

With the CentOS platform, I think we'd need to adopt a similar Docker build. If we keep with the static compiling, I think this is as simple as building a wheel normally and renaming it to manylinux1 before uploading?

**Comment by chriskuehl** [comment]
That did work: https://testpypi.python.org/pypi/dumb-init/

**Comment by asottile** [comment]
Honestly I think we can keep the same build.  If feel a little more comfortable if it ran in the official docker image,  (the script becomes unnecessary since we're python agnostic).  Probably just a one liner in the makefile?
