### ISSUE TITLE
Upload a wheel to pypi

### ISSUE THREAD

**Issue by cancan101** [Yelp/dumb-init#135]
It looks like a wheel is build-able: https://github.com/Yelp/dumb-init/pull/75 and this will make installing in Docker simpler.

**Comment by chriskuehl** [comment]
Ah yeah, @asottile added support for manylinux wheels in #131 but we never uploaded one to public PyPI. I'll do that now.

**Comment by chriskuehl** [comment]
dumb_init-1.2.0-py2.py3-none-manylinux1_x86_64.whl is uploaded, thanks! Let us know if you have any trouble using it.
