### ISSUE TITLE
pip install from MacOS

### ISSUE THREAD

**Issue by NicolasLM** [Yelp/dumb-init#152]
I often find myself installing on my MacOS development machine a bunch of dependencies of a Python project that includes dumb-init. The installation fails with:

```
$ pip install -r requirements.txt
[...]
Collecting dumb-init
  Using cached dumb-init-1.2.0.tar.gz
Installing collected packages: dumb-init
  Running setup.py install for dumb-init ... error
    Complete output from command /private/tmp/foo/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='dumb-init/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record install-record.txt --single-version-externally-managed --compile --install-headers /private/tmp/foo/venv/include/site/python3.6/dumb-init:
    running install
    running build
    running build_cexe
    creating build
    creating build/temp.macosx-10.6-intel-3.6
    cc -c dumb-init.c -o build/temp.macosx-10.6-intel-3.6/dumb-init.o
    creating build/scripts-3.6
    cc build/temp.macosx-10.6-intel-3.6/dumb-init.o -o build/scripts-3.6/dumb-init -static
    ld: library not found for -lcrt0.o
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'cc' failed with exit status 1
```

Because the C compiler does not support `-static` on MacOS, the installation of the dependencies fails.

Removing the `-static` flag from the Makefile allows to compile and use dumb-init just fine. Is there any tip to compile the package from PyPI on MacOS? Thanks!

MacOS 10.12.6
Clang Apple LLVM version 9.0.0 (clang-900.0.38)
Python 3.6.1

**Comment by asottile** [comment]
I had a patch at some point to exclude `-static` on macos, the actual important line is here:
https://github.com/Yelp/dumb-init/blob/2132d82bde8cf8e5ee132d5bc136d62937ed2d3f/setup.py#L117

perhaps we can revive that patch!

**Comment by chriskuehl** [comment]
Guessing we'd need to do something to this line: https://github.com/Yelp/dumb-init/blob/2132d82bde8cf8e5ee132d5bc136d62937ed2d3f/setup.py#L117

I wonder if there's some way we can "detect" the presence of `-static` support in the `setup.py`. I'd prefer that slightly over doing an `if platform == osx` to conditionally include that flag, but that could work as a last resort.

cc @asottile, I bet you have an idea here?

**Comment by asottile** [comment]
Yeah we can do the configure-style approach.  Here's where I've done something similar (for golang): 

https://github.com/asottile/setuptools-golang/blob/a89fa085e1c0098d10ead6396fa1426ad8a0d061/setuptools_golang.py#L34-L54

**Comment by chriskuehl** [comment]
@NicolasLM dumb-init 1.2.1 was just released with asottile's patch, can you check if that fixes the problem?

**Comment by NicolasLM** [comment]
It works perfectly, thanks!
