### ISSUE TITLE
Adding power(ppc64le) binaries to releases page

### ISSUE THREAD

**Issue by ghatwala** [Yelp/dumb-init#161]
Hi All,

I got an issue whilst building "fluentd" dockerfile on ppc64le ( power ) arch as seen here - https://travis-ci.org/ghatwala/fluentd-docker-image/jobs/377640502#L930 

The power builds are failing for debian image based fluentd dockerfile only - https://github.com/ghatwala/fluentd-docker-image/blob/master/v0.12/debian/Dockerfile#L4.  The power binaries are missing are in releases page here .

I was able to successfully build "dumb-init" from source locally on power machine using the same debian image.  let us know if following is possible - 

	1. Can we help in providing pre-built ppc64le binaries and add this binary to list of available packages on releases page.
	2. Do you'll want to build this power binary  ( via artifacts ) from jenkins at OSU/OSL - http://osuosl.org/services/powerdev/request_hosting/ . I could help configuring a job here.

let me know your views/suggestions.

**Comment by asottile** [comment]
I didn't know travis-ci supported other architectures!

Maybe we could use these to build artifacts:

https://github.com/ghatwala/fluentd-docker-image/blob/df8119745e69083b70956ad4e7494ad40b98880d/.travis.yml#L3-L5

I wonder if we could also use this to debug the issues we were seeing in #118, #138, #155

**Comment by chriskuehl** [comment]
Neat! I didn't know that either.

If we can build with Travis, I think that'd be ideal. Definitely happy to add builds for other architectures to the "Releases" tab (assuming we have a way to build them for future releases).

**Comment by ghatwala** [comment]
@asottile, @chriskuehl  - Yup , travis-ci supports power ( ppc64le) too now , currently we have done a soft beta launch. Hopefully there will be a public announcement about power support on travis-ci shortly.  
And yeah we could use travis-ci to create build artifacts for power using below  in *.travis.yml - 
```
os:
 - linux-ppc64le
```
And using these instructions here to upload artifacts to github - https://docs.travis-ci.com/user/deployment/releases/ and of course to debug the issues which u have mentioned above. 

let me know if u need anything on configuring up a job at travis-ci/power.

**Comment by chriskuehl** [comment]
We switched to Travis in #163, should be able to try this out now :)

**Comment by ghatwala** [comment]
@chriskuehl - sure , please go ahead !! , keep me posted. :)

**Comment by ghatwala** [comment]
@chriskuehl - did u try creating a travis-ci job for power , and try creating "dumb-init" binaries ( *.deb ) . Lemme know if u have any updates for me.

**Comment by chriskuehl** [comment]
Haven't had a chance to try it out yet -- it's on my list though!

**Comment by samrocketman** [comment]
@ghatwala also, if you know how to create the power binary you could also fork this repository, set up Travis CI yourself for building power binaries.

If you get something that works it would be awesome if you contributed your changes back.

**Comment by ghatwala** [comment]
@samrocketman , @chriskuehl  , @asottile  - have been able to create a power binary using this job - https://travis-ci.org/ghatwala/dumb-init/builds/386610930 and using these changes in *.travis.yml - https://github.com/ghatwala/dumb-init/blob/master/.travis.yml  ( taken on jessie env as others were giving failures. The tagged release is here - https://github.com/ghatwala/dumb-init/releases/tag/20180601112051-6bf0d8b . let me know your comments about this binary - "dumb-init_1.2.1_ppc64el.deb"

**Comment by samrocketman** [comment]
Hi @ghatwala, unfortunately I do not have a ppc based machine so I don’t think I can help validate yoyr binary.  On behalf of other ppc users thanks for you help on this effort.

**Comment by ghatwala** [comment]
Thanks @samrocketman !!! - was thinking using travis-ci ( having power support now ) , can we now think of having power binaries ( *.deb) now available at the releases page of this "dumb-init" repository . This will help me resolve my original problem statement mentioned at the beginning of this ticket. Any comments on this to conclude on this ticket ?

**Comment by chriskuehl** [comment]
Awesome, thanks for your work on this and producing a working example @ghatwala!

I'll see if I can get this hooked into our regular CI pipeline.

**Comment by samrocketman** [comment]
@ghatwala just to be clear I have no control over the dumb-init repository.  I just occasionally comment and use dumb-init myself.  @chriskuehl does have the ability and judging from his response I’m hopeful that you’ll get a desirable outcome.  Just to say that I care but I have no control.

I think it is great that you made the effort to fork this repository and accomplished getting it working.

@chriskuehl I’m not sure if you’re publishing releases automatically but I know that Travis CI supports building tags.  There’s also https://github.com/aktau/github-release project which provides a small static binary for publishing releases to GitHub.  You can use that `github-release` project if you would rather automate release from an external system (external to Travis CI).

Just my 2 cents.

**Comment by samrocketman** [comment]
@chriskuehl here’s an example of how I automate releasing in one of my projects.  https://github.com/samrocketman/jenkins-bootstrap-shared/blob/master/scripts/uploadRelease.sh

**Comment by chriskuehl** [comment]
Thanks for those examples. I'm looking into what we can do (trying to navigate the process involved around actually getting credentials not tied to an individual's account for this GitHub org).

We may end up using something like https://docs.travis-ci.com/user/uploading-artifacts/ to upload build artifacts from Travis to S3 instead, and then manually copying those to Releases when we make a new release.

Hang tight -- I'm pretty sure we can figure something out within in the next day or two.

**Comment by samrocketman** [comment]
@chriskuehl might be worth creating a service account in GitHub as well that is team shared and rotate the login when someone leaves the team.  I have a couple of service accounts on GitHub.  It’s within the GH terms of service.

**Comment by ghatwala** [comment]
@samrocketman - thanks a lot for your 2 cents :-) !!! . @chriskuehl - thanks for trying to push ppc64le artifacts to releases page as well . Will be looking here to wait on the next progress !!! :+1:

**Comment by chriskuehl** [comment]
Okay, we have Travis building for ppc64le and uploading artifacts we can use! :tada: 

Before I upload these to the "Releases" tab, can anyone (maybe @ghatwala) sanity-check either the binary or the Debian package is working? Besides Travis I don't really know how to test on this architecture :)

* Just the binary: https://yelp-travis-artifacts.s3.amazonaws.com/dumb-init/145/itest_stretch-linux-ppc64le/dist/dumb-init_1.2.1_ppc64el
* Debian package: https://yelp-travis-artifacts.s3.amazonaws.com/dumb-init/145/itest_stretch-linux-ppc64le/dist/dumb-init_1.2.1_ppc64el.deb

**Comment by chriskuehl** [comment]
Btw, thanks again @ghatwala for pushing for this and helping get Travis set up!

**Comment by ghatwala** [comment]
@chriskuehl  - Sure, you're welcome !!! Also as requested see below sanity checks done on above binary + debian installer.

**Sanity check for Binary**
```
root@f3b43f150ee9:/# arch
ppc64le

root@f3b43f150ee9:/# wget https://yelp-travis-artifacts.s3.amazonaws.com/dumb-init/145/itest_stretch-linux-ppc64le/dist/dumb-init_1.2.1_ppc64el
--2018-06-06 05:04:04--  https://yelp-travis-artifacts.s3.amazonaws.com/dumb-init/145/itest_stretch-linux-ppc64le/dist/dumb-init_1.2.1_ppc64el
Resolving yelp-travis-artifacts.s3.amazonaws.com (yelp-travis-artifacts.s3.amazonaws.com)... 52.219.24.116
Connecting to yelp-travis-artifacts.s3.amazonaws.com (yelp-travis-artifacts.s3.amazonaws.com)|52.219.24.116|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 66968 (65K) [binary/octet-stream]
Saving to: 'dumb-init_1.2.1_ppc64el'

dumb-init_1.2.1_ppc64el                      100%[===========================================================================================>]  65.40K  --.-KB/s    in 0.08s

2018-06-06 05:04:05 (772 KB/s) - 'dumb-init_1.2.1_ppc64el' saved [66968/66968]

root@f3b43f150ee9:/# chmod u+x dumb-init_1.2.1_ppc64el
root@f3b43f150ee9:/# mv dumb-init_1.2.1_ppc64el /usr/bin/dumb-init
root@f3b43f150ee9:/# whereis dumb-init
dumb-init: /usr/bin/dumb-init

root@f3b43f150ee9:/# dumb-init --version
dumb-init v1.2.1
```
**Similar sanity check for debian installer**
```
root@e7cd57f9d157:/# arch
ppc64le

root@e7cd57f9d157:/# wget https://yelp-travis-artifacts.s3.amazonaws.com/dumb-init/145/itest_stretch-linux-ppc64le/dist/dumb-init_1.2.1_ppc64el.deb
--2018-06-06 05:10:58--  https://yelp-travis-artifacts.s3.amazonaws.com/dumb-init/145/itest_stretch-linux-ppc64le/dist/dumb-init_1.2.1_ppc64el.deb
Resolving yelp-travis-artifacts.s3.amazonaws.com (yelp-travis-artifacts.s3.amazonaws.com)... 54.231.235.43
Connecting to yelp-travis-artifacts.s3.amazonaws.com (yelp-travis-artifacts.s3.amazonaws.com)|54.231.235.43|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43400 (42K) [application/x-debian-package]
Saving to: 'dumb-init_1.2.1_ppc64el.deb'

dumb-init_1.2.1_ppc64el.deb                  100%[===========================================================================================>]  42.38K  --.-KB/s    in 0.04s

2018-06-06 05:10:58 (1022 KB/s) - 'dumb-init_1.2.1_ppc64el.deb' saved [43400/43400]

root@e7cd57f9d157:/# dpkg -i dumb-init_1.2.1_ppc64el.deb
Selecting previously unselected package dumb-init.
(Reading database ... 5069 files and directories currently installed.)
Preparing to unpack dumb-init_1.2.1_ppc64el.deb ...
Unpacking dumb-init (1.2.1) ...
Setting up dumb-init (1.2.1) ...

root@e7cd57f9d157:/# whereis dumb-init
dumb-init: /usr/bin/dumb-init /usr/share/man/man1/dumb-init.1.gz

root@e7cd57f9d157:/# dumb-init --version
dumb-init v1.2.1
```

From above , sanity checks for both "dumb-init" - binary + installer passed. So you're free to upload these to the releases tab.   :100: . Thanks a lot as well for your efforts too for adding support for power.

Now just awaiting the update to the "Releases" tab.

**Comment by samrocketman** [comment]
@ghatwala #166

**Comment by chriskuehl** [comment]
@ghatwala thanks for the reminder, I've just uploaded them at https://github.com/Yelp/dumb-init/releases/tag/v1.2.1

**Comment by ghatwala** [comment]
@asottile - thanks , am already following up with travis folks on this if there's any issue to upload ppc64le build artifacts . 
@chriskuehl  - thanks a lot for uploading the power binaries to the releases page.

With that , i can close this ticket for now .
