### ISSUE TITLE
Z(s390x) binaries via Travis

### ISSUE THREAD

**Issue by james-crowley** [Yelp/dumb-init#199]
@asottile and @chriskuehl Travis now supports `s390x`. You can modify your `.travis.yml` to take advantage of this. Might make your life a little easier! 

Take a look at the [announcement](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) for some more information about the changes.

**Comment by chriskuehl** [comment]
Thanks for the heads-up!
