### ISSUE TITLE
Rename release files so that `uname -m` could be used

### ISSUE THREAD

**Issue by ifireball** [Yelp/dumb-init#201]
The files released on GitHub use rather strange names for architectures such as `amd64` (usually referred to as `x86_64`) or `ppc64el` (Usually referred to as `ppc64le`).

If standard architecture names would be used, it would be possible to download `dumb-init` with an architecture-neutral command such as:

    wget -O /usr/local/bin/dumb-init \
    https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_$(uname -m)

This is especially important for writing Dockerfiles that can be built on multiple architectures.

**Comment by asottile** [comment]
The naming that is used currently is consistent with debian's architecture naming -- you can use `dpkg --print-architecture` if you're on a debian-derivative

**Comment by ifireball** [comment]
Any solution for when you are not?

Seems that kernel-based naming would be a more neutral ground.

**Comment by chriskuehl** [comment]
Using the kernel naming probably makes the most sense for the binaries (I think the .deb naming is best left as-is). I'll make a PR to do that for future versions and for the current version I'll upload renamed copies (leaving the old ones in place as duplicates to avoid breaking anything, of course).

**Comment by chriskuehl** [comment]
So the renames are:

* `dumb-init_1.2.2_amd64` => `dumb-init_1.2.2_x86_64`
* `dumb-init_1.2.2_arm64` => `dumb-init_1.2.2_aarch64`
* `dumb-init_1.2.2_ppc64el` => `dumb-init_1.2.2_ppc64le`
* `dumb-init_1.2.2_s390x` => no change

I went ahead and re-uploaded the existing binaries under their new names for 1.2.2: https://github.com/Yelp/dumb-init/releases/tag/v1.2.2
