### ISSUE TITLE
Is this project works for virtual machine?

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [Yelp/dumb-init#205]
Are this `dumb-init` work only for docker kind of environment or it will also work for real virtual machines?

**Comment by chriskuehl** [comment]
It should work for virtual machines as it fulfills the requirements for PID 1.

Typically dumb-init is only used for single-purpose containers as it doesn't contain the kind of sophisticated process orchestration that you would normally want on a machine used to run multiple tasks, but I don't see any reason it wouldn't work. Depending on your use-case it may not be the best fit though.

**Comment by KarthikNedunchezhiyan** [comment]
@chriskuehl tnx for your response. I am trying to write a custom init script that should take care of mounting, zombies, etc. I am really confused about where to begin with. Can you help me to find a full-fledged init script that will work in VMs. It will help me to learn more.

**Comment by SwagDevOps** [comment]
You can use dumb-init with runit, or use runit alone.

I prefer to use dumb-init with runit.

I think, I will post again (soon) with better explanations and some examples.
