### ISSUE TITLE
looks like dumb-init binary missing for 1.2.3 release

### ISSUE THREAD

**Issue by chenrui333** [Yelp/dumb-init#216]
👋  it looks like dumb-init binary is missing for 1.2.3 release?

**Comment by chriskuehl** [comment]
How are you trying to download it and for what architecture? I see the binaries listed here: https://github.com/Yelp/dumb-init/releases/tag/v1.2.3

**Comment by asottile** [comment]
looks like the naming scheme changed (x86_64 instead of amd64)

**Comment by chriskuehl** [comment]
We switched to the kernel architecture naming scheme for binaries in #201. I mentioned in the release notes of the previous version that the naming had changed, but I'll add this to these notes as well.

**Comment by asottile** [comment]
ah cool, yeah that makes sense then 👍

**Comment by chenrui333** [comment]
I see, make sense. Thanks!

**Comment by chenrui333** [comment]
I see you updated the release notes, that is really helpful.
