### ISSUE TITLE
dumb-init fails on symbolic link (does it support those?)

### ISSUE THREAD

**Issue by Twiggeh** [Yelp/dumb-init#255]
I was trying to add an entrypoint to my docker image, but the entrypoint is an arg variable, arising in this issue:

[SO issue with docker interpolation issues, suggests to use symbolic links](https://stackoverflow.com/a/40903689/11864012)

The solution proposes that I would create a symbolic link and then point `dumb-init` at said symbolic link.

The only problem appears to be that dumb-init doesn't want to use the symbolic link and throws a "No such file or directory" despite it clearly existing:
![image](https://user-images.githubusercontent.com/23149166/128009706-3390dcf8-7d6f-4f0b-aef8-44531f73da2d.png)
(inside the built image)

I have tried version 1.2.2 and 1.2.5

**Comment by asottile** [comment]
what does `ls -al /usr/bin/brig` give you?

**Comment by asottile** [comment]
also the term is "symbolic link" by the way

**Comment by Twiggeh** [comment]
>also the term is "symbolic link" by the way
Thanks :D

> what does `ls -al /usr/bin/brig` give you?

`ls -l /usr/bin/service` shows that the symbolic link exists. Unfortunately I did not include `ls -l  /usr/bin/service | grep "brig"` that would have shown that the file actually exists. 

This doesn't appear to be an issue with `dumb-init` after further investigation though, because I cannot access that file in any way. It appears to be related to [Alpine ](https://stackoverflow.com/questions/68636358/file-not-found-in-alpine-container-despite-existing)/ something else, so I will close this issue :D
