### ISSUE TITLE
dumb-init returns 143 error code in docker container

### ISSUE THREAD

**Issue by GenaANTG** [Yelp/dumb-init#260]
After `docker-compose stop beanstalk` command container with `dumb-init` returns 143 exit code.

Dockerfile

```Dockerfile
FROM alpine:3.14

RUN set -xe && apk add --no-cache dumb-init beanstalkd 

EXPOSE 11300/tcp

STOPSIGNAL SIGTERM

ENTRYPOINT ["/usr/bin/dumb-init", "--", "/usr/bin/beanstalkd", "-s", "5242880", "-f", "60000"]

CMD ["-b", "/var/log"]
```
`docker-compose stop beanstalk`

<img width="1144" alt="Screenshot 2021-10-17 at 05 22 09" src="https://user-images.githubusercontent.com/12715550/137608082-4ecd8a7d-19a7-4266-8a54-3434bde0554e.png">

`docker-compose exec beanstalk ps aux` 

<img width="915" alt="Screenshot 2021-10-17 at 05 26 51" src="https://user-images.githubusercontent.com/12715550/137608260-cacce532-58dc-4ed9-baee-ee491b56f84c.png">

PID 1 is correct, dumb-init should catch the signals.

**Comment by asottile** [comment]
this seems correct to me, `dumb-init` receives the `TERM`, sends it along to its subprocesses and then exits with whatever code they have (which most often will be 143 "exited due to unhandled TERM").

here's a small example using `sleep`:

```console
$ dumb-init -vvv sleep 10000; echo $?
[dumb-init] Detached from controlling tty, but was not session leader.
[dumb-init] Child spawned with PID 20277.
[dumb-init] Unable to attach to controlling tty (errno=1 Operation not permitted).
[dumb-init] setsid complete.
[dumb-init] Received signal 15.
[dumb-init] Forwarded signal 15 to children.
[dumb-init] Received signal 17.
[dumb-init] A child with PID 20277 was terminated by signal 15.
[dumb-init] Forwarded signal 15 to children.
[dumb-init] Child exited with status 143. Goodbye.
143
```

(note that in the other terminal I ran `kill -TERM 123123` where `123123` is the pid of `dumb-init`

you can further validate by running `dumb-init` with more `--verbose` flags

**Comment by GenaANTG** [comment]
@asottile  Thanks mate! I have already complete read the documentation. I missed a point is that dumb-init catch the signals and **forwards them to children processes**. Looks like problem is still with beanstalkd, so i need write simple wrapper.

My old report: https://github.com/beanstalkd/beanstalkd/issues/527
