### ISSUE TITLE
Make giving error as  /usr/bin/ld: cannot find -lc

### ISSUE THREAD

**Issue by sawashar** [Yelp/dumb-init#269]
Hi, 
Iam trying to install dumb-init on centos but it is giving me following error while building it from source code:
cc -std=gnu99 -static -s -Wall -Werror -O3 -o dumb-init dumb-init.c
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make: *** [build] Error 1
Any help here?

**Comment by asottile** [comment]
I'd suggest googling "/usr/bin/ld: cannot find -lc" -- this isn't a problem with dumb-init but with missing packages on your system

**Comment by sawashar** [comment]
> I'd suggest googling "/usr/bin/ld: cannot find -lc" -- this isn't a problem with dumb-init but with missing packages on your system

I have glibc installed and tried things mentioned in the google search . Can you point me to a certain package missing.
