### ISSUE TITLE
[DELETED]

### ISSUE THREAD

**Issue by otterley** [Yelp/dumb-init#270]
[DELETED]

**Comment by asottile** [comment]
`dumb-init` is intentionally not featureful, I think this would extend beyond the scope of its intention as a minimal init system

also it appears to be invalid:

```console
$ xargs -0 < /proc/1/environ 
bash: /proc/1/environ: Permission denied
```

**Comment by otterley** [comment]
It's not invalid (run the same command again as root), but it turns out the workaround I had suggested won't work anyway, since unsetting environment variables does not remove them from /proc/<pid>/environment. So there's no action worth taking.

**Comment by asottile** [comment]
if you're running untrusted things as root you probably have bigger problems!
