### ISSUE TITLE
pytest 7.2.0 no longer installs py

### ISSUE THREAD

**Issue by moto-timo** [Yelp/dumb-init#286]
Since https://github.com/pytest-dev/pytest/pull/10396 the py library is
no longer installed, but dumb-init needs 'py._path'.

```
    ImportError while importing test module '/tmp/tmp.k8zSDBKT6S/dumb-init-1.2.5/tests/child_processes_test.py'.
    Hint: make sure your test modules/packages have valid Python names.
    Traceback:
    /usr/lib/python3.8/importlib/__init__.py:127: in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    tests/child_processes_test.py:10: in <module>
        from testing import is_alive
    testing/__init__.py:11: in <module>
        from py._path.local import LocalPath
    E   ModuleNotFoundError: No module named 'py._path'; 'py' is not a package
```

**Comment by asottile** [comment]
#288 is a better approach -- eliminate `py` entirely (it's deprecated after all)

**Comment by moto-timo** [comment]
@asottile agreed. Thank you for doing the right thing.

@chriskuehl it would be very helpful if you could merge this and do a release with a full source tarball, as that is what we are pulling and building (this gives you some extra Linux distro coverage, since we have a matrix of ~14 distro/version combinations).
