### ISSUE TITLE
Add man page to Debian package

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/dumb-init#38]
`help2man` can easily create a manpage given a binary with `--help` and `--version`, we can easily use this once #37 is merged.

**Comment by bukzor** [comment]
@chriskuehl does this block v1.0?

**Comment by chriskuehl** [comment]
@bukzor what is v1.0? I wasn't planning on cutting a 1.0 until we have a breaking change, in the spirit of semver. But I'd be fine with a sentimental bump to 1.0 with the intention of signaling "this is expected to be pretty stable" as well.

**Comment by bukzor** [comment]
In the spirit of semver, semver isn't in effect till 1.0
All 0.x versions can be entire rewrites with entirely different API.
See rule 4: http://semver.org/

**Comment by chriskuehl** [comment]
@bukzor ah, did not know that! I will cut a 1.0 shortly.
