### ISSUE TITLE
create, send signal to a process group

### ISSUE THREAD

**Issue by bukzor** [Yelp/dumb-init#4]
Use case is a bash script like so:

```#!bash
yes oh, hi! | pv -qL 10 &
yes error | pv -qL 10 >&2
```

When dumb-init gets sigterm (or any other signal), I want the whole process tree (bash, yes, pv, yes, pv) to get the same signal. 

Implementation:
 * on startup dumb-init initiates a process group:
   http://man7.org/linux/man-pages/man2/setsid.2.html
 * on signal, dumb-init sends that signal to the process group it created:
   http://man7.org/linux/man-pages/man2/kill.2.html

**Comment by chriskuehl** [comment]
If I'm interpreting this right, we'd probably want to add an option for this and leave the existing functionality as another option, right? Currently dumb-init basically pretends to not exist (you can stick it or even multiple copies of it in front of any command and the behavior should not be changed).

With this we might actually change behavior. For example, we might start sending signals to every uWSGI process, not just the master process, which we probably don't want.

Does adding it as an extra option sound reasonable?

**Comment by bukzor** [comment]
To your use case, I do specifically want this in the case of uWSGI as well; this solves the problem of lost java-plovr processes.

If you want an option, let's please default it on.
I imagine you'll control the option via environment variable.

IMHO I believe we will find that we never in fact want it off.
