### ISSUE TITLE
ENTRYPOINT vs CMD

### ISSUE THREAD

**Issue by alhafoudh** [Yelp/dumb-init#43]
Shouldn't `dumb-init` be used as `ENTRYPOINT` instead of `CMD`?

As I understand, default entrypoint for docker container is `/bin/sh -c`.
If you prefix your app `myapp` with `dumb-init` in `CMD`, what would be actually ran is `sh -c "dumb-init myapp"`, so PID1 would be still `sh -c`, not `dumb-init`.

**Comment by ruudud** [comment]
The "default entrypoint" is *not* `/bin/sh -c`, but if the shell form of `CMD` is used, `/bin/sh -c` is prepended to the given command.

But I agree with you that it makes sense to use `dumb-init` as (part of) `ENTRYPOINT`.

**Comment by bukzor** [comment]
Many images don't fit the use case of ENTRYPOINT, and only have a CMD
defined.

Given that you do define an ENTRYPOINT, it's correct that you'd want to put
dumb-init there, and not in CMD.

**Comment by rdsubhas** [comment]
I'm using it as the `ENTRYPOINT` and liking it much better. Because I usually override the `command` in `docker-compose.yml` for development, and remembering to add `dumb-init` everywhere is cumbersome.

**Comment by bukzor** [comment]
We'll update the README to reflect this.

--phone is hard.

**Comment by chriskuehl** [comment]
Sorry for the slow action on this, I just opened #103.
