### ISSUE TITLE
Release binary instead of DEB

### ISSUE THREAD

**Issue by rdsubhas** [Yelp/dumb-init#45]
Hi, Firstly thanks for the awesome utility. Just quickly wanted to ask: Why release a DEB, when such a compact utility like this can be released straight away as a simple binary? wget, chmod and run would be nice right?

**Comment by ctrlrsf** [comment]
To start, the deb package tells you the version of dumb-init that was compiled and the architecture it was compiled for. A deb might not be your package of choice, but managing/tracking/upgrading a simple binary over time becomes cumbersome.

**Comment by bukzor** [comment]
We can release a binary too, I'd that would be helpful. I suppose not
everyone it's on a Debian.

--phone is hard.

**Comment by chriskuehl** [comment]
I've posted binaries for old versions as well as the latest release, 1.0.0, and added links to the README.

The latest release is at https://github.com/Yelp/dumb-init/releases/download/v1.0.0/dumb-init_1.0.0_amd64

Thanks for the issue!

**Comment by rdsubhas** [comment]
Great, thanks @chriskuehl !

And @ctrlrsf the architecture doesn't really matter right? Docker runs only on 64 bit, so there would be only one arch. Please correct if I'm wrong.

**Comment by en90** [comment]
@rdsubhas

>Docker runs only on 64 bit so there would be only one arch.

No, that's not right. See e.g. http://blog.xebia.com/docker-on-a-raspberry-pi/ (though I myself have not and will not do this on my Pi).

Aside from that, even though dumb-init is made with Docker in mind, it might be useful for other purposes as well, meaning that any restrictions on which architectures Docker is able to run on should not be used by themselves to motivate not being able to run dumb-init, IMO.

Finally, a small nitpick, there are multiple different 64-bit arcitectures, so you should specify which one you mean when you talk about it, though obviously you were refering to the most popular one; amd64, aka. x86_64.

**Comment by rdsubhas** [comment]
@en90 thanks, yes I missed alternate ones like arm64, etc. anyways, got the binary for normal docker use with non-deb oses :smile:
