### ISSUE TITLE
Add "latest" tag so Dockerfile/build script doesn't need to be updated

### ISSUE THREAD

**Issue by RRAlex** [Yelp/dumb-init#48]
instead of the 0.5.0 tag:
wget https://github.com/Yelp/dumb-init/releases/download/v0.5.0/dumb-init_0.5.0_amd64.deb

make it possible to reuse the URL, maybe something like this:
wget https://github.com/Yelp/dumb-init/releases/download/latest/dumb-init_amd64.deb

(.deb or binaries)
cheers!

**Comment by bukzor** [comment]
We can't find any simple way to support this, due to github limitations (see http://stackoverflow.com/questions/24085978/github-url-for-latest-release-of-the-download-file).

Do you know of any other project(s) that do this?

**Comment by chriskuehl** [comment]
I tried pushing a "latest" tag but unfortunately couldn't find a way to make that work, either :(

**Comment by RRAlex** [comment]
Didn't realize that, but I guess this hack could work :

```
wget https://github.com/Yelp/dumb-init/releases/download$(wget -q -O - https://github.com/Yelp/dumb-init/releases/latest|grep '/[^/]*/dumb-init_[^/]*_amd64.deb' | sed "s/.*\(\/[^\/]*\/dumb-init_[^\/]*_amd64.deb\).*/\1/")
```

Yeah, not pretty...

**Comment by bukzor** [comment]
There doesn't seem to be any clean way to implement this.
