### ISSUE TITLE
Question about ENTRYPOINT use

### ISSUE THREAD

**Issue by bilalakil** [Yelp/dumb-init#54]
I'm writing up a base Dockerfile with `dumb-init` and was looking at some existing examples.

I've reached the point where I'm dealing with `ENTRYPOINT` and am a bit confused by something I've seen in [someone else's Dockerfile that uses `dumb-init`](https://github.com/cybe/docker-init/blob/master/Dockerfile).

They're using `ENTRYPOINT ["dumb-init", "--"]` - it's the second value there that I'm confused about (`"--"`).

I've tried running mine with and without it, and they both work. I'm not sure if anything behaves differently. I've looked through `dumb-init`'s source code to try and find anything about that, without success.

So is this a random typo from that author, or is anyone else using it and knows whether or not it does anything?

**Comment by asottile** [comment]
The `--` tells dumb-init to ignore the rest of the arguments after it when considering its own argument parsing.

The following is a super-contrived example, but I hope it demonstrates the difference:

```
# Install dumb-init in a virtualenv
$ virtualenv venv && . venv/bin/activate && pip install dumb-init
...
$ echo 'echo hi' > venv/bin/-V # Make an executable, on the PATH, named -V
# Just to show how it works
$ -V
hi
# Without --
$ dumb-init -V
dumb-init v1.0.0
# With --
$ dumb-init -- -V
hi
```

There are certainly less contrived examples, this was the easiest to demonstrate :)

Does this make sense?

**Comment by chriskuehl** [comment]
It's a pretty common pattern with other executables as well, e.g. to remove a file named `--help`, you can use `rm -- --help`.

**Comment by bilalakil** [comment]
Ahh fascinating! And I suppose I didn't find it in the source because it's a feature of `getopt`. Thanks a bunch for the clarification :)
