### ISSUE TITLE
dumb-init package for alpine linux

### ISSUE THREAD

**Issue by mishak87** [Yelp/dumb-init#55]
Would it be possible to add packages for alpine linux?

Now it is possible to install it via python but it would be nice to have it available in package repository same as debian.
```sh
apk --update-cache py-pip
pip install dumb-init
```

**Comment by bukzor** [comment]
Feel free to make yourself our alpine packager.
We don't really use alpine packages at all.

**Comment by bukzor** [comment]
We won't be doing this. It's a downstream issue from our standpoint.
