### ISSUE TITLE
UB in signal_handler

### ISSUE THREAD

**Issue by msavage20** [Yelp/dumb-init#58]
See section 7.14.1.1 of the C99 standard:

> If the signal occurs other than as the result of calling the abort or raise function, the
behavior is undefined if the signal handler refers to any object with static storage duration
other than by assigning a value to an object declared as volatile sig_atomic_t

`signal_handler` reads `use_setsid` and `child_pid`, which have static storage duration.

A possible solution would be to handle signals synchronously and avoid these limitations. See sigprocmask(2) and sigwait(3), or [sinit](http://git.suckless.org/sinit/tree/sinit.c) for examples.

**Comment by chriskuehl** [comment]
Thanks for reporting this and suggesting a solid fix!
