### ISSUE TITLE
Mention dependencies for building the debian package

### ISSUE THREAD

**Issue by rberlich** [Yelp/dumb-init#76]
Hi there,

just tried to build the debian package using "make builddeb" on Ubuntu 16.04. Just thought, it might be worth mentioning in the doku that (at least) the following packages need to be installed:

- devscripts (for buildep)
- musl-tools
-  debhelper 
- help2man 
- python-pytest 
- python-mock

Kind Regards,
Beet

**Comment by asottile** [comment]
I think this mentions the build dependencies: https://github.com/Yelp/dumb-init/blob/c7c6b00dd70818f118a34697a512a2feb2856ae0/debian/control#L6-L12

You usual debian way to install this is with `mk-build-deps`

**Comment by chriskuehl** [comment]
Yup, `mk-build-deps` (from `devscripts`) is the preferred way to do this. I don't think we want to duplicate the actual build dependencies in the README, but I'll add some additional info to the README about how to build (and install the deps)!
