### ISSUE TITLE
Switch from Travis to CircleCI

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/dumb-init#8]
With [circleci](https://circleci.com/) we should be able to run our integration tests in CI (they rely on Docker).

**Comment by kentwills** [comment]
Travis now has support for docker, http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/

**Comment by chriskuehl** [comment]
That looks great, actually. I'll look into that.

**Comment by chriskuehl** [comment]
Closing this since #13 was merged
