### ISSUE TITLE
Running dumb-init as "non-root"

### ISSUE THREAD

**Issue by rberlich** [Yelp/dumb-init#96]
Hi there,

I have created a container with dumb-init as ENTRYPOINT and a USER-statement right before that in the Dockerfile, i.e. dumb-init runs as non-root. As all processes running inside of the container run under the same user-id (as they are spawned by dumb-init), I cannot see a reason why dumb-init could not just perform the work it is designed to do (i.e. reap zombies and relay signals), even when running as non-root. After all, it has all necessary permissions to deal with processes under the same user-id.

Is this thinking correct, or should dumb-init indeed run as root ?

In this case, one would have to explicitly switch the user once dumb-init has started (e.g. using gosu), so as not to run other processes as root.

Thanks and Kind Regards,
Beet

**Comment by asottile** [comment]
We're using dumb-init as (almost exclusively) non-root.  Are you seeing any issues or is this more of a question?

**Comment by rberlich** [comment]
Hi Anthony,

> Am 12.07.2016 um 17:46 schrieb Anthony Sottile <notifications@github.com>:
> 
> We're using dumb-init as (almost exclusively) non-root. Are you seeing any issues or is this more of a question?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/Yelp/dumb-init/issues/96#issuecomment-232090657>, or mute the thread <https://github.com/notifications/unsubscribe/ASlWX4ymiDgt1ClZQhGa3bW_XoWqKdIhks5qU7bsgaJpZM4JKTmo>.
> 

no, I am not seeing issues in my tests. Its only that I have never seen a Unix system with a process ID 1 running as non-root, so I was wondering whether there were any fundamental reasons why this might be a problem (e.g. any system calls only available to root, which PID 1 needs to access, etc.).

Thanks for your help and sharing your experiences,
Beet

**Comment by asottile** [comment]
Heh, true most unix init systems run as root.  dumb-init has no problems running as non-root as long as it is only dealing with processes it has permission to deal with (usually in the docker case they're going to be the same user).
