### ISSUE TITLE
Name change ?

### ISSUE THREAD

**Issue by rberlich** [Yelp/dumb-init#97]
Hi there,

any chance of a name change for dumb-init, e.g. to smart-init ? I find dumb-init pretty awesome and feel that it might profit from being named differently:-)

Kind Regards,
Beet

**Comment by asottile** [comment]
Lol! It's "dumb" because it is a minimal,  not fully featured init system.

**Comment by samrocketman** [comment]
I like dumb-init.  It got the point across for me with the name alone.  For containers where I require more robust init system because of requirements I use dumb-init with a patched version of `runit`.
