### ISSUE TITLE
Be polite, respectful and reasonable

### ISSUE THREAD

**Issue by onlyjob** [Yelp/dumb-init#99]
I was shocked to see how minor yet meaningful contribution #84 by @jirutka was turned down in a rude way by team member @bukzor ("closed as propaganda") which was then promptly justified by another team member @chriskuehl with no apologies. Comment(s) were subsequently removed and conversation locked without any reasoning or discussion. Nobody was given a chance for '+1' or '-1'.

That kind of rude and unfair treatment of contributors (and contributions) makes me wonder whether it was a good idea to get involved into this project. Contributors deserve more respect. Dear _dumb-init_ team, please mind your manners and don't turn down contributions for ill-advised reasons.
Everyone would benefit from more appreciation to each others' efforts. Please be reasonable, respectful and polite.

**Comment by samrocketman** [comment]
I don't necessarily disagree that it shouldn't have been accepted.  However, I do agree it could have been handled with more tact from the start.  Though, I didn't find @chriskuehl's comment to be bad or rude.

**Comment by chriskuehl** [comment]
@onlyjob @samrocketman 

Thanks for the ticket and for the discussion above. We definitely appreciate the people who have contributed to dumb-init (including your work), and I'm sorry you felt our responses weren't respectful. That definitely wasn't our intention, but I can see that we didn't handle it as graciously as we should have.

It's important to us that contributors feel like they're welcome and are treated with respect. We'll be careful in the future to make sure this is the case.

**Comment by onlyjob** [comment]
Thanks, @chriskuehl.
